[build]
  command = "npm run build"
  publish = "build"

[context.production]
  environment = { NODE_ENV = '16.15.0'}

[dev]
  command = 'svelte-kit dev'

[[headers]]
  for = "/*.woff"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff"

[[headers]]
  for = "/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/font-woff2"
