backend:
  name: git-gateway
  branch: main

local_backend: true
media_folder: static/images
public_folder: /images
site_url: https://sshawn.com
display_url: https://sshawn.com
logo_url: https://res.cloudinary.com/cupbots/image/upload/w_100,f_auto/v1656947127/sshawn-logo.png

collections:
  - name: 'books'
    label: 'Book'
    create: true
    preview: false
    sort: 'date:desc'
    format: 'frontmatter'
    summary: "{{date | date('DD MMM YY')}} - {{title}}"
    folder: 'src/lib/content/books'
    fields:
      - {
          label: 'Title',
          name: 'title',
          widget: string
        }
      - {
          label: 'Date',
          name: 'date',
          widget: datetime,
          format: 'YYYY-MM-DD'
        }
      - {
          label: 'Rating',
          name: 'rating',
          required: false,
          widget: number
        }
      - {
          label: 'Author',
          name: 'author',
          widget: string
        }
      - {
          label: 'Featured Image',
          name: 'featuredImage',
          required: false,
          widget: image
        }
      - {
          label: 'Summary',
          name: 'summary',
          required: false,
          widget: markdown,
          minimal: true
        }
      - {
          label: 'Book URL',
          name: 'bookURL',
          required: false,
          widget: string
        }
      - {
          label: 'Body',
          name: 'body',
          widget: markdown
        }

  - name: 'blog'
    label: 'Blog'
    create: true
    sort: 'date:desc'
    format: 'frontmatter'
    summary: "{{date | date('DD MMM YY')}} - {{title}}"
    folder: 'src/lib/content/blog'
    fields:
      - {
          label: 'Title',
          name: 'title',
          widget: string
        }
      - {
          label: 'Subtitle',
          name: 'subtitle',
          required: false,
          widget: string
        }
      - {
          label: 'Date',
          name: 'date',
          widget: datetime,
          format: 'YYYY-MM-DD'
        }
      - label: 'Category'
        name: 'category'
        default: ''
        widget: 'relation'
        collection: 'categories'
        search_fields: ['title']
        value_field: 'title'
        display_fields: ['title']
        multiple: true
      - {
          label: 'Featured Image',
          name: 'featuredImage',
          required: false,
          widget: image
        }
      - {
          label: 'Image Credit',
          name: 'imageCredit',
          required: false,
          widget: string
        }
      - {
          label: 'Image Credit URL',
          name: 'imageCreditURL',
          required: false,
          widget: string
        }
      - {
          label: 'Summary',
          name: 'summary',
          required: false,
          widget: markdown,
          minimal: true
        }
      - {
          label: 'Body',
          name: 'body',
          widget: markdown
        }

  - name: 'now'
    label: 'Now'
    editor:
      preview: false
    files:
      - label: 'Now'
        name: 'now'
        format: frontmatter
        file: 'src/lib/content/now/now.md'
        fields:
          - {
              label: 'Body',
              name: 'body',
              widget: markdown,
            }
      - label: 'Projects'
        name: 'projects'
        widget: 'list'
        file: 'src/lib/content/now/project.json'
        fields:
        - {
            label: 'Title',
            name: 'title',
            widget: string,
            required: true
          }
        - {
            label: 'URL',
            name: 'url',
            widget: string,
            required: false
          }
        - {
            label: 'Body',
            name: 'body',
            widget: string,
            required: false
          }
        - {
            label: 'Logo',
            name: 'logo',
            required: false,
            widget: image
          }
        - {
            label: 'Featured Image',
            name: 'featuredImage',
            required: false,
            widget: image
          }
      - label: 'Other projects'
        name: 'other-projects'
        widget: 'list'
        file: 'src/lib/content/now/other-projects.json'
        fields:
        - {
            label: 'Title',
            name: 'title',
            widget: string,
            required: true
          }
        - {
            label: 'URL',
            name: 'url',
            widget: string,
            required: false
          }

  - label: 'Pages'
    name: 'pages'
    files:
      - label: 'About'
        name: 'about'
        format: frontmatter
        file: 'src/lib/content/about.md'
        fields:
          - {
              label: 'Title',
              name: 'title',
              widget: string
            }
          - {
              label: 'Body',
              name: 'body',
              widget: markdown,
            }

      - label: 'Projects'
        name: 'projects'
        file: 'src/lib/content/now/projects.json'
        fields:
          - label: 'Projects'
            name: 'projects'
            widget: 'list'
            fields:
              - {
                  label: 'Title',
                  name: 'title',
                  widget: string,
                  required: false
                }
              - {
                  label: 'Logo',
                  name: 'logo',
                  widget: image,
                  required: false
                }
              - {
                  label: 'Body',
                  name: 'text',
                  widget: markdown,
                  required: false
                }
              - {
                  label: 'Image',
                  name: 'image',
                  widget: image,
                  required: false
                }

  - label: 'Category'
    name: 'categories'
    create: true
    format: "json"
    folder: 'src/lib/content/categories'
    fields:
      - { label: 'Title', name: 'title', widget: string }
      - { label: 'Description', name: 'description', widget: string, required: false }

